import { HeaderXPWA } from './Header.js';
import { LogoXPWA } from './Logo.js';
import { ContentXPWA } from './Content.js';
import { MenuXPWA } from './menu/Menu.js';
import { FooterXPWA } from './Footer.js';
import { BlockXPWA } from './Block.js';
import { CloseXPWA } from './Close.js';
import { ButtonXPWA } from './button/Button.js';
import { StubXPWA } from './Stub.js';
